### ISSUE TITLE
Sequence number out of sync after fixed intervals

### ISSUE THREAD

**Issue by rohandm29** [connamara/quickfixn#461] opened 2017-12-11 16:37 UTC
The Sequence number goes out of sync after fixed intervals and keeps resetting.

Config has below -
ResetOnLogon=N
ResetOnDisconnect=N
RefreshOnLogon=N
ValidateFieldsOutOfOrder=N
ResetSeqNumFlag=N

Below are the logs - 

```
                        8=FIXT.1.1|9=65|35=0|34=1620|49=CTHR1002|52=20171211-11:23:21.889|56=TRAX|57=APA|10=110|
20171211-11:23:26.407 : 8=FIXT.1.1|9=58|35=0|34=1293|49=TRAX|52=20171211-11:23:26.371|56=CTHR1002|10=241|
20171211-11:23:55.098 : 8=FIXT.1.1|9=65|35=0|34=1621|49=CTHR1002|52=20171211-11:23:52.629|56=TRAX|57=APA|10=107|
20171211-11:24:03.146 : 8=FIXT.1.1|9=74|35=1|34=1622|49=CTHR1002|52=20171211-11:24:03.146|56=TRAX|57=APA|112=TEST|10=118|
20171211-11:24:03.255 : 8=FIXT.1.1|9=67|35=0|34=1294|49=TRAX|52=20171211-11:24:03.208|56=CTHR1002|112=TEST|10=255|
20171211-11:24:36.182 : 8=FIXT.1.1|9=65|35=0|34=1623|49=CTHR1002|52=20171211-11:24:33.526|56=TRAX|57=APA|10=105|
20171211-11:24:36.291 : 8=FIXT.1.1|9=58|35=0|34=1295|49=TRAX|52=20171211-11:24:36.248|56=CTHR1002|10=248|
20171211-11:33:47.627 : 8=FIXT.1.1|9=84|35=A|34=1624|49=CTHR1002|52=20171211-11:33:47.564|56=TRAX|57=APA|98=0|108=30|1137=9|10=223|
20171211-11:33:49.721 : 8=FIXT.1.1|9=74|35=A|34=1|49=TRAX|52=20171211-11:33:49.664|56=CTHR1002|98=0|108=30|1137=9|10=201|
20171211-11:33:49.753 : 8=FIXT.1.1|9=117|35=5|34=1625|49=CTHR1002|52=20171211-11:33:49.753|56=TRAX|57=APA|58=MsgSeqNum too low, expecting 1296 but received 1|10=222|
20171211-11:34:48.308 : 8=FIXT.1.1|9=84|35=A|34=1626|49=CTHR1002|52=20171211-11:34:48.293|56=TRAX|57=APA|98=0|108=30|1137=9|10=226|
20171211-11:34:48.933 : 8=FIXT.1.1|9=74|35=A|34=4|49=TRAX|52=20171211-11:34:48.869|56=CTHR1002|98=0|108=30|1137=9|10=211|
20171211-11:34:48.933 : 8=FIXT.1.1|9=117|35=5|34=1627|49=CTHR1002|52=20171211-11:34:48.933|56=TRAX|57=APA|58=MsgSeqNum too low, expecting 1296 but received 4|10=227|
```

**Comment by andyast** [comment] 2020-08-31 15:16
I know this is a SUPER OLD issue but I'm seeing the exact same issue... did you ever get anywhere on this?

**Comment by gbirchmeier** [comment] 2020-08-31 15:31
I don't think anyone has looked at this issue ever.  I must have been busy when it came in and never got around to it.

However, looking at it now, I think it's a pretty poor bug report.  Minimal description, and just a wall of log, and no followup.  (Did he solve it?)   If I was doing an issue cleanup, I would just close it.

But now that you've called my attention to it, @andyast, I'll take a look.  Can you tell me about what you're seeing in a little more detail?  (What is the fixed interval?)

Also, which version of QF/n are you using?  If you're using an old version, or a Nuget that we didn't create ([see list here](http://quickfixn.org/download/) I will probably ask you to update.

**Comment by gbirchmeier** [comment] 2020-08-31 15:40
The original submitter's (let's call him Subby) report looks like a configuration issue.  Subby's app sends a login with seqnum=N, and the counterparty responds with seqnum=1, and then Subby's app gets mad about it.

Looks to me like Subby's counterparty wants to reset on logon, and Subby needs to configure his app accordingly -- it should be ResetOnLogon=Y.

I am closing this issue, because the original submission is not a bug.

@andyast, if your situation is different and you need further follow up, please ask on the QF/n mailing list, or ask your question on StackOverflow.

**Closed by gbirchmeier** 2020-08-31 15:40 UTC

**Comment by rohandm29** [comment] 2020-08-31 15:54
Sorry about that. I was getting seq out of sync whatever config values i tried. 
I had tried different combinations for ResetOnLogon and ResetSeqNumFlag with no luck.

I no longer work for the organisation. Thanks.

**Comment by gbirchmeier** [comment] 2020-08-31 16:12
For what it's worth, I do apologize for missing this the first time around.
