### ISSUE TITLE
Timing issue loading DLLs

### ISSUE THREAD

**Issue by baffled** [connamara/quickfixn#864] opened 2024-07-02 11:12 UTC
There is a potential timing issue if you start more than one connection at the same time, each creating a DefaultMessageFactory.

When discovering the QuickFix.FIXxx.dll libraries, LoadLocalDlls() kicks out the second (and any subsequent) thread to prevent it reloading the same assemblies into memory. But if the first thread has not finished iterating through all the libraries and exited the function, the second thread will end up querying a truncated list and won't have all the factories in its list. That leads to an incorrect BeginString error at runtime when parsing message groups (and took a load of tracking down).

Better to lock the DefaultMessageFactory.LoadLocalDlls() function to ensure it completes before the second thread hits the loadFlag test.

**Comment by gbirchmeier** [comment] 2024-07-02 15:55
Thank you for reporting this!  I see it in the code, and agree with your interpretation of the situation.

The original coder did implement a loadFlag to ensure that two threads wouldn't run this function concurrently... but, in line with your explanation, second/subsequent threads should be forced to wait until the first thread's call completes the task before they are allowed to return.

(Also, that `@` variable is kind of gross and unnecessary.)

I've seen/heard this incorrect-BeginString error happen capriciously, but not in consistent ways that have made it easy to follow-up on.  But I think this could be the cause!  I'm very happy you tracked this down 👍  and I will try to get the fix in the next release (which shouldn't be too far off I hope)

**Comment by gbirchmeier** [comment] 2024-07-30 14:34
Hey @baffled , did you ever take a look at my PR fix for this issue?

**Closed** 2024-08-27 21:21 UTC

**Comment by baffled** [comment] 2024-09-02 08:50
Hi Grant

 

So sorry for the radio silence on this. Unfortunately I’m (temporarily) no longer involved in the project, my client having decided to do without my services for a while. This happens from time to time, and it’s a bit of a game - their PMs have already been in contact asking me to do plenty of other project work so no doubt I’ll be back on it when they need something 🤣.

 

Best Regards

Brian
