### ISSUE TITLE
Incorrect processing of Logout message

### ISSUE THREAD

**Issue by AngryShaDoW** [connamara/quickfixn#640] opened 2020-07-28 15:27 UTC
Why QuickFix.Session when receive Logout message create new instance of it (instead of send it as is)? If i try to extend this message by new fields, then I will fail, because all added data will be lost

**Comment by gbirchmeier** [comment] 2020-07-28 16:21
Closing because not a bug.

Please see http://quickfixn.org/help for where to ask questions.

**Comment by AngryShaDoW** [comment] 2020-07-28 17:05
It's a bug. You create new instance of message, copy values only from some fields(Text field) of old message and lose other data. Please take a look to QuickFix.Session::GenerateLogout(Message other, string text)

**Comment by gbirchmeier** [comment] 2020-07-28 17:40
Write up a nice bug report, and I'll take a look.  Tell me what you're actually doing, what you expect to happen, and what actually happens.  Show me some code excerpts of what you're trying to do.

We don't get paid to maintain this project, so I'm not gonna spend an hour deciphering vague reports.

**Comment by AngryShaDoW** [comment] 2020-07-29 08:06
Thank you for your time.
My case is very simple:
- I extend the fix44 Logout message with few fields (that describes logout reason)
- I have used my custom msg factory, that create correct msg type (this is ok)
- But at QuickFix.Session::GenerateLogout(Message other, string text) logout msg was recreate new instance and set only custom text and lose all data that original msg contains:

            Message logout = msgFactory_.Create(this.SessionID.BeginString, Fields.MsgType.LOGOUT);
            InitializeHeader(logout);
            if (text != null && text.Length > 0)
                logout.SetField(new Fields.Text(text));
            if (other != null && this.EnableLastMsgSeqNumProcessed)
            {
                try
                {
                    logout.Header.SetField(new Fields.LastMsgSeqNumProcessed(other.Header.GetInt(Tags.MsgSeqNum)));
                }
                catch (FieldNotFoundException)
                {
                    this.Log.OnEvent("Error: No message sequence number: " + other);
                }
            }
            state_.SentLogout = SendRaw(logout, 0);
            return state_.SentLogout;

(And even without extension original text of logout will be lose)
I can offer fix for this problem by pull request, but first I would like to know: this(I mean recreation of msg instance)  is done on purpose (if so, why?) or it is accident?

**Comment by gbirchmeier** [comment] 2021-01-25 21:21
I'm will admit that QF/n doesn't make it easy to customize Logout such as you are doing.  It is a rather uncommon thing to do.  QF/n makes it easy to edit non-admin messages, but not as easy with admin messages.  And the logout... I've *never* seen anyone want to edit that one.

If you want to customize the Logout message, probably the best way is to catch it in the `ToApp()` callback, like this:

```
public void ToAdmin(Message message, SessionID sessionID)
{
    if(message.Header.GetField(Tags.MsgType)==MsgType.LOGOUT)
    {
        // set custom fields with "msg.SetField(whatever)"
    }
}
```

You'll have to decide yourself how this callback is going to get the logout value from your other code.  You'll need to use some external variable.

But at this time, we are are not interested in changing the engine to support such a niche situation.

**Closed by gbirchmeier** 2021-01-25 21:21 UTC
