### ISSUE TITLE
How to install QuickFix/n (Tutorial for Beginners) ?

### ISSUE THREAD

**Issue by Johnn78** [connamara/quickfixn#734] opened 2022-06-02 13:54 UTC
I want to occupy with Quickfix/n for first time. Can someone write with simple words how to do it ? The official site should be the https://quickfixengine.org/n/ but the details which has, are not addressed for newbie. I downloaded the project from here : https://github.com/connamara/quickfix. I installed Ruby, dotnet (i think that I have installed it properly) & visual studio 2017. When i tried to load the "QuickFIXn.sln" it appeared that can't load the project due to missing components & by going in visual studio at tools/Get Tools and Features I selected some addons like desktop developement in .NET & in C++ etc.. and now the project is appearred to be loaded properly but when I run the build.bat from F5 or via Green arrow (AcceptanceTest) (it has two options about Framework net461 & netcoreapp2.1) then ended with error "he program '["random number"] AcceptanceTest.exe' has exited with code 2 (0x2). " if net461 is selected or "The program '["random number"] dotnet.exe' has exited with code 2 (0x2)" if netcoreapp2.1 is selected. Why does this happen ? & Why the official site does NOT have a simple tutorial how to implement the FIX protocol via Quickfix in simple steps ? Thanks in advance !

**Comment by gbirchmeier** [comment] 2022-06-02 13:58
QuickFIX/n is not an application.  It's an engine.  It's a dll (actually a couple dlls) that you import into an application that you have to write.

If you are not a programmer, then QF/n is not for you.  If you are a programmer, then this page should get you started: http://quickfixn.org/tutorial/creating-an-application.html

Closing this issue, because it's not a bug.

**Closed by gbirchmeier** 2022-06-02 13:58 UTC

**Comment by Johnn78** [comment] 2022-06-02 14:08
I am programmer. I see that it has some example in your given link. What template should I choose in visual studio & how to import these two dll files ?

**Comment by gbirchmeier** [comment] 2022-06-02 14:28
Maybe you should use one of the NuGet packages: http://quickfixn.org/download/

As to your other questions: I am sorry, but these are beginner C# questions.  I mean no disrespect, but I do not have time to offer you free training.

**Comment by mgatny** [comment] 2022-06-02 16:47
If you downloaded/cloned https://github.com/connamara/quickfix then you have the wrong repo (https://github.com/connamara/quickfix is the c++ version of quickfix).

You want https://github.com/connamara/quickfixn (which is indeed where you are right now).

One of the simplest ways to get started is to build and run the example applications: https://github.com/connamara/quickfixn/tree/master/Examples

Specifically, I recommend running the Executor example app, and connecting to it with the TradeClient example app.

**Comment by Johnn78** [comment] 2022-06-03 16:00
Update ! I resolved the 36 errors. Now I face only one error "CS0121	The call is ambiguous between the following methods or properties: 'QuickFix.Fields.Converters.Dat.Fields.Converters.DateTimeConverter.Nanosecond(System.DateTime)' and 'QuickFix.Fields.Converters.DateTimeConverter.Nanosecond(System.DateTime)'	QuickFix(netstandard2.0)"
How to resolve this ?
