### ISSUE TITLE
I have to work with version FIXT.1.1

### ISSUE THREAD

**Issue by prozerran** [connamara/quickfixn#730] opened 2022-05-05 08:48 UTC
Alright, most the time, the brokers i work with are FIX4.2, but now there is  a broker using version FIXT.1.1
But the project solution only has version from 4.0-5.0 + 5.0 sp1 + sp2
So how should I go about doing this?
Is there an upgrade or extension I can add to support FIXT.1.1
or do I need to modify FIX5.0 SP2 to accommodate the difference?

I assume FIXT.1.1 and FIX5.0SP2 should be very similar and i should be able to make the necessary changes to make work?
I prefer to work in FIX4.2. Can that also work? What do you guys suggest?

**Comment by raymondjstone** [comment] 2022-05-05 11:41
As I understand it FIXT just allows you to use a variety of FIX versions in the same session, it is in effect a transport layer

**Comment by gbirchmeier** [comment] 2022-05-05 14:42
The project totally has FIXT in it: https://github.com/connamara/quickfixn/tree/master/spec/fix

In FIX5+, they split the admin messages (Login, Logout, Heartbeat, etc)  into their own separate dictionary.  (I don't know why they thought this was a good idea.)

Your config now has to specify `TransportDataDictionary=path/to/FIXT1.1.xml` and `AppDataDictionary=path/to/FIX50<xx>.xml`.

Closing this, because it's not a bug.

**Closed by gbirchmeier** 2022-05-05 14:42 UTC
