### ISSUE TITLE
CheckValidFormat throws exception while trying to convert an empty field and CheckFieldsHaveValues set to 'false'.

### ISSUE THREAD

**Issue by gkorobkin** [connamara/quickfixn#405] opened 2016-07-22 22:54 UTC
That broken FIX message:
_8=FIX.4.4|9=293|35=8|34=14|49=FIX-SC-FEED|50=STDCHFX|52=20160719-19:45:36.869|56=BCSC|57=365900501|115=StdCh|1=365900501|15=USD|17=10|31=1.36796|32=10000|39=2|54=2|55=EUR/USD|60=20140128-03:09:17.000|64=20140130|75=20140128|109=Markit1|194=1.36796|195=|198=No QID on comments field!|527=00UGCZD|20000=7310.16|10=153|_
was parsed by **QuickFix/C++** but **QuickFix/N** fails.

**Comment by gbirchmeier** [comment] 2020-06-11 18:30
Argh, it took me too long to figure out the cause.  Thanks for including the actual exception, OP! \</sarcasm>  Also, the message OP gives as an example is invalid because it's missing required fields.

First I thought this OP was mistaken, because I've tested this before (see #282).  Very nearly closed this as a false report, but luckily I dug further.

My previous tests passed because I tested it with a *string* field.  Empty string fields work just fine, because the empty string is a valid value.  OP sees an error because field 195 is a **float**, and C# won't convert empty-string to float implicity.

Will dig into C++ engine and see how it handles empty-field value conversions.

**Comment by gbirchmeier** [comment] 2020-06-11 19:07
(The sarcasm probably wasn't totally warranted, since it did take me 4 years to get to this issue.  I'll own that.)

**Comment by gbirchmeier** [comment] 2020-06-12 18:42
fixed by #613, documentation updates in 809cbc5 / 714ed02 / 725b1a6

Please note, with this fix, the engine will accept the message and pass it up to the application callbacks, **BUT** the user will still see an error if they try to extract the field as a non-string.  The engine will not convert empty strings to int/decimal/boolean/datetime etc.

App code can use e.g. `msg.Price.Obj` to get the field as a string and then check it's length and decide to interpret empty strings as 0 or whatever.

**Closed** 2020-06-12 18:47 UTC
Labels: bug
